config/routes.rb
Rails.application.routes.draw do
  get "/metanew",  to:'metamons#new'
  get "/metamonshow",  to:'metamons#show'
  get 'sessions/new'
  root "static_pages#home"
  get  "/help",    to: "static_pages#help"
  get  "/sign",  to: "scores#new"
  get  "/main",  to: "scores#main"
  get  "/daiichi",  to: "scores#daiichi"
  get  "/show",  to: "scores#show"
  get  "/tesuto",  to: "champs#new"
  get  "/hontouroku",  to: "temps#name"
  get  "/tempcon",  to: "temps#confirm"
  get  "/signup",  to: "users#new"
  get  "/usershow",  to: "users#show"
  get  "/usercon",  to: "users#confirm"
  get  "/kateindex",  to: "kategoris#index"
  get  "/useredit",  to: "users#edit"
  get    "/login",   to: "sessions#new"
  get    "/templenew",   to: "templates#new"
  get    "/templesearch",   to: "templates#search"
  get    "/tempshow",   to: "temps#show"
  get    "/scoeasy",   to: "scores#easy"
  get    "/which",   to: "metamons#which"
  
  get    "/easyscore",   to: "scores#easyscore"
  get    "/easymain",   to: "scores#easymain"
  get    "/easysituation",   to: "scores#easysituation"
  get    "/easysynergy",   to: "scores#easysynergy"
  get    "/easykihon",   to: "scores#easykihon"

  get    "/easyscoreedit",   to: "scores#easyscoreedit"
  get    "/easyedit",   to: "scores#easyedit"
  get    "/easysituationedit",   to: "scores#easysituationedit"
  get    "/easysynergyedit",   to: "scores#easysynergyedit"
  get    "/easykihonedit",   to: "scores#easykihonedit"

  get    "/tempedit",   to: "champs#edit"
  get    "/tempnameedit",   to: "temps#edit"
  get    "/catesgow",   to: "categoris#show"
  get    "/metaedit",   to: "metamons#edit"

  get "/get_position", to: "scores#get_position"
  get "/get_synergyposition", to: "scores#get_synergyposition"
  get "/get_situationposition", to: "scores#get_situationposition"
  get "/get_kihonposition", to: "scores#get_kihonposition"
  get "/get_positionedit", to: "scores#get_positionedit"
  get "/get_synergypositionedit", to: "scores#get_synergypositionedit"
  get "/get_situationpositionedit", to: "scores#get_situationpositionedit"
  get "/get_kihonpositionedit", to: "scores#get_kihonpositionedit"
  
  post '/update_or_create_data', to: 'scores#update_or_create_data'
  post '/update_or_create_synergydata', to: 'scores#update_or_create_synergydata'
  post '/update_or_create_situationdata', to: 'scores#update_or_create_situationdata'
  post '/update_or_create_dataedit', to: 'scores#update_or_create_dataedit'
  post '/update_or_create_synergydataedit', to: 'scores#update_or_create_synergydataedit'
  post '/update_or_create_situationdataedit', to: 'scores#update_or_create_situationdataedit'
  post '/update_or_create_kihondata', to: 'scores#update_or_create_kihondata'
  post '/update_or_create_kihondataedit', to: 'scores#update_or_create_kihondataedit'
  post "/login", to: "sessions#create"
  post 'reset_temp', to: 'temps#reset_temp'
  get 'edit_temp/:temp_id', to: 'champs#edit_temp', as: 'edit_temp'
  get 'edit_initiate/:truemetamonid', to: 'scores#edit_initiate', as: 'edit_initiate'
  post 'reset_score', to: 'scores#reset_score'
  post '/hontouroku', to: 'kategoris#create'
  resources :easyscores
  resources :scores
  resources :scoremaps
  resources :heros
  resources :users
  resources :champs
  resources :temps
  resources :metamons
  resources :templates
  resources :joukyous
  resources :kategoris
  resources :users do
    member do
      get :update_doing_temp
      get :update_editing_temp
    end
  end
  resources :scores do
    collection do
      post :create1
      post :create2
      post :create3
    end
  end
  get 'champs/:name/image', to: 'champs#show_image'
  resources :users do
    post 'set_tempting_false', on: :collection
  end
  resources :joukyous do
    post 'creation', on: :collection
    member do
      delete :destroy_edit_joukyou
    end
  end
  resources :champs do
    post 'set_tempting_true', on: :collection
    post 'set_editting_true', on: :collection
  
    member do
      delete :destroy_edit
    end
  end
  delete "/logout",  to: "sessions#destroy"
end

app/models/champ.rb
class Champ < ApplicationRecord
  has_one_attached :image
  belongs_to :temp, optional: true
end

app/models/checkwork.rb
class Checkwork < ApplicationRecord
end

app/models/easycounter.rb
class Easycounter < ApplicationRecord
end

app/models/easykihon.rb
class Easykihon < ApplicationRecord
end

app/models/easyscore.rb
class Easyscore < ApplicationRecord
end

app/models/easysituation.rb
class Easysituation < ApplicationRecord
end

app/models/easysynergy.rb
class Easysynergy < ApplicationRecord
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :champs, inverse_of: :group
end

app/models/hero.rb
class Hero < ApplicationRecord
end

app/models/image_word.rb
# app/models/image_word.rb
class ImageWord < ApplicationRecord
  validates :image_name, presence: true
  validates :word, presence: true
end

app/models/joukyou.rb
class Joukyou < ApplicationRecord
  has_one_attached :image
  belongs_to :temp, optional: true
end

app/models/kategori.rb
class Kategori < ApplicationRecord
  has_many :temps
  has_one_attached :image
  def self.ransackable_attributes(auth_object = nil)
    %w(name)
  end
end

app/models/metamon.rb
class Metamon < ApplicationRecord
  has_many :scores,dependent: :destroy
  has_one_attached :image
  belongs_to :user ,optional: true
  def self.ransackable_attributes(auth_object = nil)
    %w(name gamename setumei metaid)
  end
end

app/models/metum.rb
class Metum < ApplicationRecord
end

app/models/score.rb
class Score < ApplicationRecord
  belongs_to :metamon, optional: true
end

app/models/score_map.rb
class ScoreMap < ApplicationRecord
end

app/models/temp.rb
class Temp < ApplicationRecord
  belongs_to :user
  belongs_to :kategori, optional: true
  has_one_attached :image
  has_many :champs, dependent: :destroy
  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "id", "name", "temp_id", "updated_at", "user_id", "usertemp_id", "kategori_id"]
  end
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: true
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
  has_many :metamons,dependent: :destroy
  has_many :temps
  has_one_attached :image
  def self.ransackable_attributes(auth_object = nil)
    %w(created_at doingtempid doingtempuserid editingmetaid editingtempid editting email id ifnewmeta ifnewtemp metating name tempting updated_at)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @metamon = current_user.metamons.build if logged_in?
    @latemetamons = Metamon.order(created_at: :desc).limit(6)
    @kategoritachi= Kategori.order(created_at: :desc).limit(6)
  end
  def help
  end
end

app/helpers/new_helper.rb
module NewHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/static_pages/help.html.erb
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<link href="https://fonts.googleapis.com/css2?family=M+PLUS+1p&display=swap" rel="stylesheet">
  <style>
    .metamon-container {
  display: flex;
  flex-wrap: wrap;
  justify-content: center;
  gap: 10px;
  border-radius: 0; /* 背景の角を消す */
}

.metamon-item {
  position: relative;
  width: 150px;
  height: 150px;
  border-radius: 10px; /* 要素の角を丸くする */
  overflow: hidden; /* 子要素の角を丸くする */
}

.metamon-image {
  width: 100%;
  height: 100%;
  background-color: white;
}

.metamon-link {
  position: absolute;
  bottom: 0;
  width: 100%;
  height: 20%;
  background-color: black;
  color: white;
  text-align: center;
  line-height: 30px;
}

.metamon-name {
  color: white;
}
    body {
      font-family: 'M PLUS 1p', sans-serif;
      font-weight: bold;
    }

    p, a ,h1{
      font-family: 'M PLUS 1p', sans-serif;
      font-weight: bold;
    }
    .btn-lg {
  padding: 10px 16px;
  font-size: 24px;
  line-height: 1.3333333;
  background-color: white; /* ボタンの背景色を白に */
  color: black; /* テキストの色を黒に */
  margin-right: 10px; /* ボタン間の余白を追加 */
  border: 10px solid #ccc; /* ボーダーを追加 */
}

.icon {
  display: block;
  margin: 0 auto;
  width: 33%;
}

  </style>
</head>
<h1>無限の考え方<br>
MYMETAへようこそ</h1>
<p>MYMETAは、あなたのゲームピックに対する考え「メタ」を作成したり、他のユーザーの「メタ」を使ってゲームピックを有利に進めたりすることができる情報共有サイトです。<br>
<h1>最新のメタ</h1>
<div class="metamon-container">
  <% @latemetamons.each do |metamon| %>
    <div class="metamon-item">
      <% if metamon.image.attached? %>
        <%= image_tag metamon.image.variant(resize_to_fill: [100, 100]).processed, class: 'metamon-image' %>
      <% else %>
        <%= image_tag '本の無料アイコン素材2.png', size: '100x100', class: 'metamon-image' %>
      <% end %>
      <div class="metamon-link">
        <%= link_to metamon.name, {controller: "scores", action: "easymain", usertemp_id: metamon.tempuser_id, user_id: metamon.user_id, metamon_id: metamon.truemetamonid}, class: 'metamon-name' %>
      </div>
    </div>
  <% end %>
</div>
<h1>探す</h1>
<div class="metamon-container">
  <% @kategoritachi.each do |metamon| %>
    <div class="metamon-item">
      <% if metamon.image.attached? %>
        <%= image_tag metamon.image.variant(resize_to_fill: [100, 100]).processed, class: 'metamon-image' %>
      <% else %>
        <%= image_tag 'ゲームの素材.png', size: '100x100', class: 'metamon-image' %>
      <% end %>
      <div class="metamon-link">
        <%= link_to metamon.name, class: 'metamon-name' %>
      </div>
    </div>
  <% end %>
</div>
<p>気になるゲームのメタはありませんか？</p>
<br>
<p>
<%= link_to usercon_path, class: "btn btn-lg btn-primary" do %>
  ユーザーを探す
  <%= image_tag("人物の無料素材.png", class: "icon") %>
<% end %>
<%= link_to kateindex_path, class: "btn btn-lg btn-primary" do %>
  ゲームを探す
  <%= image_tag("ゲームの素材.png", class: "icon") %>
<% end %>
<%= link_to metamonshow_path, class: "btn btn-lg btn-primary" do %>
  メタを探す
  <%= image_tag("虫眼鏡のアイコン.png", class: "icon") %>
<% end %>
</p>
<h1>作る</h1>
<p>
<% if current_user %>
  <%= link_to daiichi_path, class: "btn btn-lg btn-primary" do %>
    メタを作る
    <%= image_tag("スパナのアイコン素材.png", class: "icon") %>
  <% end %>
  <% if current_user.tempting%>
  <%= link_to tesuto_path, class: "btn btn-lg btn-primary" do %>
    テンプレートを作る(作成中)
    <%= image_tag("登山アイコン4.png", class: "icon") %>
    <% end %>
    <% else %>
    <%= link_to tesuto_path, class: "btn btn-lg btn-primary" do %>
    テンプレートを作る
    <%= image_tag("登山アイコン4.png", class: "icon") %>
    <% end %>
  <% end %>
<% else %>
  <%= link_to login_path, class: "btn btn-lg btn-primary" do %>
    メタを作る
    <%= image_tag("スパナのアイコン素材.png", class: "icon") %>
  <% end %>
  <%= link_to login_path, class: "btn btn-lg btn-primary" do %>
    テンプレートを作る
    <%= image_tag("登山アイコン4.png", class: "icon") %>
  <% end %>
<% end %>
</p>