config/routes.rb
Rails.application.routes.draw do
  get "/metanew",  to:'metamons#new'
  get "/metamonshow",  to:'metamons#show'
  get 'sessions/new'
  root "static_pages#home"
  get  "/help",    to: "static_pages#help"
  get  "/sign",  to: "scores#new"
  get  "/main",  to: "scores#main"
  get  "/daiichi",  to: "scores#daiichi"
  get  "/show",  to: "scores#show"
  get  "/tesuto",  to: "champs#new"
  get  "/hontouroku",  to: "temps#name"
  get  "/tempcon",  to: "temps#confirm"
  get  "/signup",  to: "users#new"
  get  "/usershow",  to: "users#show"
  get  "/usercon",  to: "users#confirm"
  get  "/kateindex",  to: "kategoris#index"
  get  "/useredit",  to: "users#edit"
  get    "/login",   to: "sessions#new"
  get    "/templenew",   to: "templates#new"
  get    "/templesearch",   to: "templates#search"
  get    "/tempshow",   to: "temps#show"
  get    "/scoeasy",   to: "scores#easy"
  get    "/which",   to: "metamons#which"
  
  get    "/easyscore",   to: "scores#easyscore"
  get    "/easymain",   to: "scores#easymain"
  get    "/easysituation",   to: "scores#easysituation"
  get    "/easysynergy",   to: "scores#easysynergy"
  get    "/easykihon",   to: "scores#easykihon"

  get    "/easyscoreedit",   to: "scores#easyscoreedit"
  get    "/easyedit",   to: "scores#easyedit"
  get    "/easysituationedit",   to: "scores#easysituationedit"
  get    "/easysynergyedit",   to: "scores#easysynergyedit"
  get    "/easykihonedit",   to: "scores#easykihonedit"

  get    "/tempedit",   to: "champs#edit"
  get    "/tempnameedit",   to: "temps#edit"
  get    "/catesgow",   to: "categoris#show"
  get    "/metaedit",   to: "metamons#edit"

  get "/get_position", to: "scores#get_position"
  get "/get_synergyposition", to: "scores#get_synergyposition"
  get "/get_situationposition", to: "scores#get_situationposition"
  get "/get_kihonposition", to: "scores#get_kihonposition"
  get "/get_positionedit", to: "scores#get_positionedit"
  get "/get_synergypositionedit", to: "scores#get_synergypositionedit"
  get "/get_situationpositionedit", to: "scores#get_situationpositionedit"
  get "/get_kihonpositionedit", to: "scores#get_kihonpositionedit"
  
  post '/update_or_create_data', to: 'scores#update_or_create_data'
  post '/update_or_create_synergydata', to: 'scores#update_or_create_synergydata'
  post '/update_or_create_situationdata', to: 'scores#update_or_create_situationdata'
  post '/update_or_create_dataedit', to: 'scores#update_or_create_dataedit'
  post '/update_or_create_synergydataedit', to: 'scores#update_or_create_synergydataedit'
  post '/update_or_create_situationdataedit', to: 'scores#update_or_create_situationdataedit'
  post '/update_or_create_kihondata', to: 'scores#update_or_create_kihondata'
  post '/update_or_create_kihondataedit', to: 'scores#update_or_create_kihondataedit'
  post "/login", to: "sessions#create"
  post 'reset_temp', to: 'temps#reset_temp'
  get 'edit_temp/:temp_id', to: 'champs#edit_temp', as: 'edit_temp'
  get 'edit_initiate/:truemetamonid', to: 'scores#edit_initiate', as: 'edit_initiate'
  post 'reset_score', to: 'scores#reset_score'
  post '/hontouroku', to: 'kategoris#create'
  resources :easyscores
  resources :scores
  resources :scoremaps
  resources :heros
  resources :users
  resources :champs
  resources :temps
  resources :metamons
  resources :templates
  resources :joukyous
  resources :kategoris
  resources :users do
    member do
      get :update_doing_temp
      get :update_editing_temp
    end
  end
  resources :scores do
    collection do
      post :create1
      post :create2
      post :create3
    end
  end
  get 'champs/:name/image', to: 'champs#show_image'
  resources :users do
    post 'set_tempting_false', on: :collection
  end
  resources :joukyous do
    post 'creation', on: :collection
    member do
      delete :destroy_edit_joukyou
    end
  end
  resources :champs do
    post 'set_tempting_true', on: :collection
    post 'set_editting_true', on: :collection
  
    member do
      delete :destroy_edit
    end
  end
  delete "/logout",  to: "sessions#destroy"
end

app/models/champ.rb
class Champ < ApplicationRecord
  has_one_attached :image
  belongs_to :temp, optional: true
end

app/controllers/champs_controller.rb
class ChampsController < ApplicationController
  def new
    @champ = Champ.new
    @joukyou = Joukyou.new
    @champl = Champ.where(temp_id: current_user.ifnewtemp, user_id: current_user.id)
    @joukyoul = Joukyou.where(temp_id: current_user.ifnewtemp, user_id: current_user.id)
  end
  def edit
    @champ = Champ.new
    @joukyou = Joukyou.new
    @champl = Champ.where(temp_id: current_user.editingtempid, user_id: current_user.id)
    @joukyoul = Joukyou.where(temp_id: current_user.editingtempid, user_id: current_user.id)
  end
  def edit_temp
    temp_id = params[:temp_id]
    current_user.update_columns(editting: true)
    current_user.update_columns(editingtempid: temp_id)
    redirect_to tempedit_path
  end

  def set_tempting_true
    current_user.update_columns(tempting: true)
    @champ = Champ.new(champ_params)
    @champ.user_id = current_user.id
    @champ.temp_id =  current_user.ifnewtemp
    if @champ.save
      redirect_to tesuto_path
    else
      logger.error current_user.errors.full_messages
    end
  end

  def set_editting_true
    current_user.update(editting: true)
    @champ = Champ.new(champ_params)
    @champ.user_id = current_user.id
    @champ.temp_id =  current_user.editingtempid
    if @champ.save
      redirect_to tempedit_path
    else
    end
  end

  def update_or_create_data
    # パラメータを取得
    name = params[:name]
    champ_name = params[:champ_name]
    point = params[:point]
  
    # モデルのインスタンスを取得または作成し、データベースを更新
    your_model = Easycounter.find_or_initialize_by(name1: name, name2: champ_name)
    your_model.update(x: point)
  
    render json: { status: 'success' }
  end

  def show_image
    champ = Champ.find_by(name: params[:name])
    redirect_to rails_blob_path(champ.image, disposition: "inline") if champ&.image.attached?
  end

  def destroy_edit
    @champ = Champ.find(params[:id])
    @champ.destroy
    redirect_to tempedit_path
  end
    
  def destroy
    @champ = Champ.find(params[:id])
    @champ.destroy
    redirect_to tesuto_path, notice: "Score deleted successfully."
  end
  def tesuto
    if current_user.tempting=true
    @champl = currentuser.temps.where(temp_id:current_user.ifnewtemp)
    end
  end
  def create
    @champ = Champ.new(champ_params)
    @champ.user_id = current_user.id
    @champ.temp_id = current_user.ifnewtemp
    if @champ.save
      redirect_to tesuto_path
    else
      render 'new'
    end
  end

  private

    def champ_params
      params.require(:champ).permit(:name, :champid, :image)
    end
    
end

app/views/champs/edit.html.erb
<h1>テンプレートを編集する</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with(model: @champ, url: set_editting_true_champs_path, method: :post) do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :image %>
      <%= f.file_field :image %>

      <%= f.submit "Add new champ", class: "btn btn-primary" %>
      <%= button_to "Edit", tempedit_path, method: :get, class: "btn btn-primary", style: "flex-shrink: 0; margin-left: 10px;" %>
    <% end %>
  </div>
</div>

<div class="d-flex flex-row flex-wrap">
  <% @champl.each do |champ| %>
    <div class="d-inline-flex align-items-center mb-3 mr-3">
      <% if champ.image.attached? %>
        <%= image_tag champ.image.variant(resize_to_fill: [100, 100]).processed, class: "mr-3" %>
      <% end %>
      <span><%= champ.name %></span>
      <span class="ml-2"><%= champ.champid %></span>
      <%= button_to "Delete", destroy_edit_champ_path(champ), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger ml-2" %>
    </div>
  <% end %>
</div>


<%= form_with(model: @joukyou, url: creation_joukyous_path) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :image %>
  <%= f.file_field :image %>

  <%= f.submit "Add new jokyou", class: "btn btn-primary" %>
<% end %>


<div class="d-flex flex-row flex-wrap">
  <% @joukyoul.each do |joukyou| %>
    <div class="d-inline-flex align-items-center mb-3 mr-3">
      <% if joukyou.image.attached? %>
        <%= image_tag joukyou.image.variant(resize_to_fill: [100, 100]).processed, class: "mr-3" %>
      <% end %>
      <span><%= joukyou.name %></span>
      <%= button_to "Delete", destroy_edit_joukyou_joukyou_path(joukyou), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger ml-2" %>
    </div>
  <% end %>
</div>













<%= link_to "名前の編集",tempnameedit_path%>

app/views/champs/new.html.erb
<h1>テンプレートを作成</h1>
<h1>キャラクター</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with(model: @champ, url: set_tempting_true_champs_path, method: :post) do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :image %>
      <%= f.file_field :image %>

      <%= f.submit "新しいヒーローを追加", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

<div class="d-flex flex-row flex-wrap">
  <% @champl.each do |champ| %>
    <div class="d-inline-flex align-items-center mb-3 mr-3">
      <% if champ.image.attached? %>
        <%= image_tag champ.image.variant(resize_to_fill: [100, 100]).processed, class: "mr-3" %>
      <% end %>
      <span><%= champ.name %></span>
      <span class="ml-2"><%= champ.champid %></span>
      <%= button_to "Delete", champ_path(champ), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger ml-2" %>
    </div>
  <% end %>
</div>

<h1>Situation</h1>
<%= form_with(model: @joukyou, url: joukyous_path) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :image %>
  <%= f.file_field :image %>

  <%= f.submit "新しい状況を追加", class: "btn btn-primary" %>
<% end %>


<div class="d-flex flex-row flex-wrap">
  <% @joukyoul.each do |joukyou| %>
    <div class="d-inline-flex align-items-center mb-3 mr-3">
      <% if joukyou.image.attached? %>
        <%= image_tag joukyou.image.variant(resize_to_fill: [100, 100]).processed, class: "mr-3" %>
      <% end %>
      <span><%= joukyou.name %></span>
      <%= button_to "Delete", joukyou_path(joukyou), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger ml-2" %>
    </div>
  <% end %>
</div>













<%= link_to "完成！", hontouroku_path, class: "btn btn-warning", style: "font-size: 1.2em; padding: 10px 20px;" %>
<%= button_to "テンプレートを完全に削除", reset_temp_path, method: :post, data: { confirm: "Are you sure?" }, class: "btn btn-danger" %>