config/routes.rb
Rails.application.routes.draw do
  get "/metanew",  to:'metamons#new'
  get "/metamonshow",  to:'metamons#show'
  get 'sessions/new'
  root "static_pages#home"
  get  "/help",    to: "static_pages#help"
  get  "/sign",  to: "scores#new"
  get  "/main",  to: "scores#main"
  get  "/daiichi",  to: "scores#daiichi"
  get  "/show",  to: "scores#show"
  get  "/tesuto",  to: "champs#new"
  get  "/hontouroku",  to: "temps#name"
  get  "/tempcon",  to: "temps#confirm"
  get  "/signup",  to: "users#new"
  get  "/usershow",  to: "users#show"
  get  "/usercon",  to: "users#confirm"
  get  "/kateindex",  to: "kategoris#index"
  get  "/useredit",  to: "users#edit"
  get    "/login",   to: "sessions#new"
  get    "/templenew",   to: "templates#new"
  get    "/templesearch",   to: "templates#search"
  get    "/tempshow",   to: "temps#show"
  get    "/scoeasy",   to: "scores#easy"
  get    "/which",   to: "metamons#which"
  
  get    "/easyscore",   to: "scores#easyscore"
  get    "/easymain",   to: "scores#easymain"
  get    "/easysituation",   to: "scores#easysituation"
  get    "/easysynergy",   to: "scores#easysynergy"
  get    "/easykihon",   to: "scores#easykihon"

  get    "/easyscoreedit",   to: "scores#easyscoreedit"
  get    "/easyedit",   to: "scores#easyedit"
  get    "/easysituationedit",   to: "scores#easysituationedit"
  get    "/easysynergyedit",   to: "scores#easysynergyedit"
  get    "/easykihonedit",   to: "scores#easykihonedit"

  get    "/tempedit",   to: "champs#edit"
  get    "/tempnameedit",   to: "temps#edit"
  get    "/catesgow",   to: "categoris#show"
  get    "/metaedit",   to: "metamons#edit"

  get "/get_position", to: "scores#get_position"
  get "/get_synergyposition", to: "scores#get_synergyposition"
  get "/get_situationposition", to: "scores#get_situationposition"
  get "/get_kihonposition", to: "scores#get_kihonposition"
  get "/get_positionedit", to: "scores#get_positionedit"
  get "/get_synergypositionedit", to: "scores#get_synergypositionedit"
  get "/get_situationpositionedit", to: "scores#get_situationpositionedit"
  get "/get_kihonpositionedit", to: "scores#get_kihonpositionedit"
  
  post '/update_or_create_data', to: 'scores#update_or_create_data'
  post '/update_or_create_synergydata', to: 'scores#update_or_create_synergydata'
  post '/update_or_create_situationdata', to: 'scores#update_or_create_situationdata'
  post '/update_or_create_dataedit', to: 'scores#update_or_create_dataedit'
  post '/update_or_create_synergydataedit', to: 'scores#update_or_create_synergydataedit'
  post '/update_or_create_situationdataedit', to: 'scores#update_or_create_situationdataedit'
  post '/update_or_create_kihondata', to: 'scores#update_or_create_kihondata'
  post '/update_or_create_kihondataedit', to: 'scores#update_or_create_kihondataedit'
  post "/login", to: "sessions#create"
  post 'reset_temp', to: 'temps#reset_temp'
  get 'edit_temp/:temp_id', to: 'champs#edit_temp', as: 'edit_temp'
  get 'edit_initiate/:truemetamonid', to: 'scores#edit_initiate', as: 'edit_initiate'
  post 'reset_score', to: 'scores#reset_score'
  post '/hontouroku', to: 'kategoris#create'
  resources :easyscores
  resources :scores
  resources :scoremaps
  resources :heros
  resources :users
  resources :champs
  resources :temps
  resources :metamons
  resources :templates
  resources :joukyous
  resources :kategoris
  resources :users do
    member do
      get :update_doing_temp
      get :update_editing_temp
    end
  end
  resources :scores do
    collection do
      post :create1
      post :create2
      post :create3
    end
  end
  get 'champs/:name/image', to: 'champs#show_image'
  resources :users do
    post 'set_tempting_false', on: :collection
  end
  resources :joukyous do
    post 'creation', on: :collection
    member do
      delete :destroy_edit_joukyou
    end
  end
  resources :champs do
    post 'set_tempting_true', on: :collection
    post 'set_editting_true', on: :collection
  
    member do
      delete :destroy_edit
    end
  end
  delete "/logout",  to: "sessions#destroy"
end

app/models/score.rb
class Score < ApplicationRecord
  belongs_to :metamon, optional: true
end

app/controllers/scores_controller.rb
class ScoresController < ApplicationController
  def show
  end
  def edit_initiate
    meta_id = params[:truemetamonid]
    themeta=Metamon.where(user_id: current_user.id, truemetamonid:meta_id).first
    current_user.update_columns(editting: true)
    current_user.update_columns(editingmetaid: meta_id)
    current_user.update_columns(editing_meta_temp_id: themeta.temp_id)
    current_user.update_columns(editing_meta_temp_user_id: themeta.tempuser_id)
    redirect_to easyedit_path
  end
  
  

  def reset_score
    Easykihon.where(user_id: current_user.id, meta_id: current_user.ifnewmeta).destroy_all
    Easycounter.where(user_id: current_user.id, meta_id: current_user.ifnewmeta).destroy_all
    Easysynergy.where(user_id: current_user.id, meta_id: current_user.ifnewmeta).destroy_all
    Easysituation.where(user_id: current_user.id, meta_id: current_user.ifnewmeta).destroy_all
    current_user.update_columns(metating: false)
    redirect_to root_path, notice: 'Meta has been reset.'
  end
  def easykihon
    @special_situation = "kihon"
    @champs = Champ.where(user_id: current_user.doingtempuserid, temp_id: current_user.doingtempid)
    @easykihons = Easykihon.where(name1: @special_situation, user_id: current_user.id, meta_id: current_user.ifnewmeta)  
    @positions = @easykihons.each_with_object({}) do |easykihon, positions|
      @champs.each do |champ|
        if easykihon.name2 == champ.name
          positions[champ.name] = { x: easykihon.x, y: easykihon.y }
        end
      end
    end
  end

  def easykihonedit
    @special_situation = "kihon"
    @champs = Champ.where(user_id: current_user.editing_meta_temp_user_id, temp_id: current_user.editing_meta_temp_id)
    @easykihons = Easykihon.where(name1: @special_situation, user_id: current_user.id, meta_id: current_user.editingmetaid)  
    @positions = @easykihons.each_with_object({}) do |easykihon, positions|
      @champs.each do |champ|
        if easykihon.name2 == champ.name
          positions[champ.name] = { x: easykihon.x, y: easykihon.y }
        end
      end
    end
  end
  
  def easysituation
    @special_situation = Joukyou.find(params[:format])
    @situation = Joukyou.where(user_id:current_user.doingtempuserid , temp_id:current_user.doingtempid )
    @champs = Champ.where(user_id: current_user.doingtempuserid, temp_id: current_user.doingtempid)

    @easysituations = Easysituation.where(name1: @special_situation.name, user_id: current_user.id, meta_id: current_user.ifnewmeta)

    @positions = @easysituations.each_with_object({}) do |easysituation, positions|
      @champs.each do |champ|
        if easysituation.name2 == champ.name
          positions[champ.name] = { x: easysituation.x, y: easysituation.y }
        end
      end
    end
  end
  def easysituationedit
    @special_situation = Joukyou.find(params[:format])
    @situation = Joukyou.where(user_id:current_user.editing_meta_temp_user_id , temp_id:current_user.editing_meta_temp_id)
    @champs = Champ.where(user_id: current_user.editing_meta_temp_user_id, temp_id: current_user.editing_meta_temp_id)

    @easysituations = Easysituation.where(name1: @special_situation.name, user_id: current_user.id, meta_id: current_user.editingmetaid)

    @positions = @easysituations.each_with_object({}) do |easysituation, positions|
      @champs.each do |champ|
        if easysituation.name2 == champ.name
          positions[champ.name] = { x: easysituation.x, y: easysituation.y }
        end
      end
    end
  end
  def easyscore
    @special_champ = Champ.find(params[:format])
    @other_champs = Champ.where(user_id: current_user.doingtempuserid, temp_id: current_user.doingtempid).where.not(id: @special_champ.id)

    @easycounters = Easycounter.where(name1: @special_champ.name, user_id: current_user.id, meta_id: current_user.ifnewmeta)

    @positions = @easycounters.each_with_object({}) do |easycounter, positions|
    @other_champs.each do |other_champ|
      if easycounter.name2 == other_champ.name
        positions[other_champ.name] = { x: easycounter.x, y: easycounter.y }
      end
    end
  end
  end
  def easyscoreedit
    @special_champ = Champ.find(params[:format])
    @other_champs = Champ.where(user_id: current_user.editing_meta_temp_user_id, temp_id: current_user.editing_meta_temp_id).where.not(id: @special_champ.id)

    @easycounters = Easycounter.where(name1: @special_champ.name, user_id: current_user.id, meta_id: current_user.editingmetaid)

    @positions = @easycounters.each_with_object({}) do |easycounter, positions|
    @other_champs.each do |other_champ|
      if easycounter.name2 == other_champ.name
        positions[other_champ.name] = { x: easycounter.x, y: easycounter.y }
      end
    end
  end
  end
  def easysynergy
    @special_champ = Champ.find(params[:format])
    @other_champs = Champ.where(user_id: current_user.doingtempuserid, temp_id: current_user.doingtempid).where.not(id: @special_champ.id)

    @easysynergys = Easysynergy.where(name1: @special_champ.name, user_id: current_user.id, meta_id: current_user.ifnewmeta)

    @positions = @easysynergys.each_with_object({}) do |easysynergy, positions|
    @other_champs.each do |other_champ|
      if easysynergy.name2 == other_champ.name
        positions[other_champ.name] = { x: easysynergy.x, y: easysynergy.y }
      end
    end
  end
  end
  def easysynergyedit
    @special_champ = Champ.find(params[:format])
    @other_champs = Champ.where(user_id: current_user.doingtempuserid, temp_id: current_user.doingtempid).where.not(id: @special_champ.id)

    @easysynergys = Easysynergy.where(name1: @special_champ.name, user_id: current_user.id, meta_id: current_user.editingmetaid)

    @positions = @easysynergys.each_with_object({}) do |easysynergy, positions|
    @other_champs.each do |other_champ|
      if easysynergy.name2 == other_champ.name
        positions[other_champ.name] = { x: easysynergy.x, y: easysynergy.y }
      end
    end
  end
  end
  def destroy
    @score = Score.find(params[:id])
    @score.destroy
    redirect_to scores_path, notice: "Score deleted successfully."
  end
  def easymain
    @hero=Hero.all
    klee = Metamon.find_by(truemetamonid: params[:metamon_id])
    insta_temp_id = klee.temp_id
    @sex2=Champ.where(user_id: params[:usertemp_id],temp_id: insta_temp_id)
    @situations=Joukyou.where(user_id: params[:usertemp_id],temp_id: insta_temp_id)
    @sex=Score.where(user_id: params[:user_id], metamon_id: params[:metamon_id])
    @testcham=Champ.where(user_id: params[:user_id],temp_id: insta_temp_id)
    @score = Score.new
    gon.wesg = @sex
    gon.champ = @sex2
    @metamonidcheck=params[:metamon_id]
    @userdoingtemp=params[:user_id]
    @easycounters = Easycounter.where(user_id: params[:user_id], meta_id: params[:metamon_id])
    @easysynergys = Easysynergy.where(user_id: params[:user_id], meta_id: params[:metamon_id])
    @easysituations = Easysituation.where(user_id: params[:user_id], meta_id: params[:metamon_id])
    @easykihons = Easykihon.where(user_id: params[:user_id], meta_id: params[:metamon_id])
    gon.counter = @easycounters
    gon.synergy = @easysynergys
    gon.situation = @easysituations
    gon.kihon = @easykihons
  end
  def main
    @hero=Hero.all
    klee = Metamon.find(params[:metamon_id])
    insta_temp_id = klee.temp_id
    @sex2=Champ.where(user_id: params[:user_id],temp_id: insta_temp_id)
    @sex=Score.where(user_id: params[:user_id], metamon_id: params[:metamon_id])
    @testcham=Champ.where(user_id: params[:user_id],temp_id: insta_temp_id)
    @score = Score.new
    gon.wesg = @sex
    gon.vct = @sex2
    @metamonidcheck=params[:metamon_id]
    @userdoingtemp=params[:user_id]
  end
  def get_position
    user_id = current_user.id
    meta_id = current_user.ifnewmeta
    easycounter = Easycounter.find_by(name1: params[:name1], name2: params[:name2], user_id: user_id, meta_id: meta_id)
    render json: { x: easycounter.x, y: easycounter.y }
  end
  def get_synergyposition
    user_id = current_user.id
    meta_id = current_user.ifnewmeta
    easysynergy = Easysynergy.find_by(name1: params[:name1], name2: params[:name2], user_id: user_id, meta_id: meta_id)
    render json: { x: easysynergy.x, y: easysynergy.y }
  end
  def get_situationposition
    user_id = current_user.id
    meta_id = current_user.ifnewmeta
    easysituation = Easysituation.find_by(name1: params[:name1], name2: params[:name2], user_id: user_id, meta_id: meta_id)
    render json: { x: easysituation.x, y: easysituation.y }
  end
  def get_kihonposition
    user_id = current_user.id
    meta_id = current_user.ifnewmeta
    easykihon = Easykihon.find_by(name2: params[:name2], user_id: user_id, meta_id: meta_id)
    render json: { x: easykihon.x, y: easykihon.y }
  end
  def get_positionedit
    user_id = current_user.id
    meta_id = current_user.editingmetaid
    easycounter = Easycounter.find_by(name1: params[:name1], name2: params[:name2], user_id: user_id, meta_id: meta_id)
    render json: { x: easycounter.x, y: easycounter.y }
  end
  def get_synergypositionedit
    user_id = current_user.id
    meta_id = current_user.editingmetaid
    easysynergy = Easysynergy.find_by(name1: params[:name1], name2: params[:name2], user_id: user_id, meta_id: meta_id)
    render json: { x: easysynergy.x, y: easysynergy.y }
  end
  def get_situationpositionedit
    user_id = current_user.id
    meta_id = current_user.editingmetaid
    easysituation = Easysituation.find_by(name1: params[:name1], name2: params[:name2], user_id: user_id, meta_id: meta_id)
    render json: { x: easysituation.x, y: easysituation.y }
  end
  def get_kihonpositionedit
    user_id = current_user.id
    meta_id = current_user.editingmetaid
    easykihon = Easykihon.find_by(name2: params[:name2], user_id: user_id, meta_id: meta_id)
    render json: { x: easykihon.x, y: easykihon.y }
  end
  def update_or_create_data
    # パラメータを取得
    name1 = params[:name1]
    name2 = params[:name2]
    x = params[:x].to_f 

app/helpers/scores_helper.rb
module ScoresHelper
end

app/views/scores/daiichi.html.erb
<style>
.btn-container {
  display: flex;
  justify-content: space-around;
  flex-wrap: wrap;
}
.btn-custom {
  font-size: 2em;
  padding: 10px 16px;
  margin: 20px;
  flex: 1 0 auto;
  min-width: 300px;
  background-color: white; /* ボタンの背景色を白に */
  color: black; /* テキストの色を黒に */
  border: none; /* ボタンの枠線を消す */
}
</style>

<div class="btn-container">
  <%= link_to tesuto_path, class: "btn btn-lg btn-primary btn-custom" do %>
    自分でテンプレートから作る
    <%= image_tag("登山アイコン4.png", class: "icon") %>
  <% end %>
  <%= link_to tempcon_path, class: "btn btn-lg btn-primary btn-custom" do %>
    既存のテンプレートを使って作る
    <%= image_tag("スパナのアイコン素材.png", class: "icon") %>
  <% end %>
</div>

app/views/scores/easy.html.erb
<h1>Counter</h1>
<% @sewo.each do |champ| %>
  <%= champ.name %>
  <% if champ.image.attached? %>
    <%= link_to easyscore_path(champ) do %>
      <%= image_tag champ.image.variant(resize_to_fill: [100, 100]).processed, class: "mr-3" %>
    <% end %>
  <% end %>
<% end %>
<h1>synergy</h1>
<% @sewo.each do |champ| %>
  <%= champ.name %>
  <% if champ.image.attached? %>
    <%= link_to easysynergy_path(champ) do %>
      <%= image_tag champ.image.variant(resize_to_fill: [100, 100]).processed, class: "mr-3" %>
    <% end %>
  <% end %>
<% end %>
<h1>situation</h1>
<% @situation.each do |champ| %>
  <%= champ.name %>
  <% if champ.image.attached? %>
    <%= link_to easysituation_path(champ) do %>
      <%= image_tag champ.image.variant(resize_to_fill: [100, 100]).processed, class: "mr-3" %>
    <% end %>
  <% end %>
<% end %>
<h1>Base</h1>
<%= link_to "ベースを決める", easykihon_path, class: "btn btn-lg btn-primary" %>

<br>新しく作った時のmetaのid
<%=current_user.ifnewmeta %>
<br>現在メタを作ってる時のテンプレートユーザー
<%=current_user.doingtempuserid %>
<br>テンプレートのid
<%=current_user.doingtempid%>
<%= link_to "完成", metanew_path, class: "btn btn-lg btn-primary" %>
<%= button_to "メタを完全に削除", reset_score_path, method: :post, data: { confirm: "Are you sure?" }, class: "btn btn-danger" %>

app/views/scores/easyedit.html.erb
<h1>Counter</h1>
<% @sewo.each do |champ| %>
  <%= champ.name %>
  <% if champ.image.attached? %>
    <%= link_to easyscoreedit_path(champ) do %>
      <%= image_tag champ.image.variant(resize_to_fill: [100, 100]).processed, class: "mr-3" %>
    <% end %>
  <% end %>
<% end %>
<h1>synergy</h1>
<% @sewo.each do |champ| %>
  <%= champ.name %>
  <% if champ.image.attached? %>
    <%= link_to easysynergyedit_path(champ) do %>
      <%= image_tag champ.image.variant(resize_to_fill: [100, 100]).processed, class: "mr-3" %>
    <% end %>
  <% end %>
<% end %>
<h1>situation</h1>
<% @situation.each do |champ| %>
  <%= champ.name %>
  <% if champ.image.attached? %>
    <%= link_to easysituationedit_path(champ) do %>
      <%= image_tag champ.image.variant(resize_to_fill: [100, 100]).processed, class: "mr-3" %>
    <% end %>
  <% end %>
<% end %>
<h1>Base</h1>
<%= link_to "ベースを決める", easykihonedit_path, class: "btn btn-lg btn-primary" %>
<%= link_to "名前を変更する", metaedit_path, class: "btn btn-lg btn-primary" %>

app/views/scores/new.html.erb
<h1>Scores#new</h1>

<p>Find me in app/views/scores/new.html.erb</p>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with(model: Score.new, url: create1_scores_path) do |f| %>
      <%= f.label :me %>
      <%= f.select :me, @sex2.pluck(:name) %>

      <%= f.label :synergy %>
      <%= f.select :enemy, @sex2.pluck(:name) %>

      <%= f.label :point %>
      <%= f.text_field :point %>

      <%= f.submit "Add", class: "btn btn-primary" %>
    <% end %>
    <%= form_with(model: Score.new, url: create2_scores_path) do |f| %>
      <%= f.label :advantage%>
      <%= f.select :me, @sex2.pluck(:name) %>

      <%= f.label :disadvantage %>
      <%= f.select :enemy, @sex2.pluck(:name) %>

      <%= f.label :point %>
      <%= f.text_field :point %>

      <%= f.submit "Add", class: "btn btn-primary" %>
    <% end %>
    <%= form_with(model: Score.new, url: create3_scores_path) do |f| %>
      <%= f.label :me%>
      <%= f.select :me, @sex2.pluck(:name) %>

      <%= f.label :situation %>
      <%= f.select :enemy, @situation.pluck(:name) %>

      <%= f.label :point %>
      <%= f.text_field :point %>

      <%= f.submit "Add", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

synergy
  <% @synergy.each do |scoret| %>
  <%= content_tag :div, class: "score-item", style: "display: flex; align-items: center;" do %>
    <%= content_tag :div, "#{scoret.me}, #{scoret.enemy}, #{scoret.point},#{scoret.SC} ", class: "score-info", style: "flex: 1;" %>
    <%= button_to "Delete", score_path(scoret), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger", style: "flex-shrink: 0; margin-left: 0px;" %>
  <% end %>
<% end %>
counter
<% @counter.each do |scoret| %>
  <%= content_tag :div, class: "score-item", style: "display: flex; align-items: center;" do %>
    <%= content_tag :div, "#{scoret.me}, #{scoret.enemy}, #{scoret.point},#{scoret.SC} ", class: "score-info", style: "flex: 1;" %>
    <%= button_to "Delete", score_path(scoret), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger", style: "flex-shrink: 0; margin-left: 0px;" %>
  <% end %>
<% end %>
situation
<% @scomaps.each do |scoret| %>
  <%= content_tag :div, class: "score-item", style: "display: flex; align-items: center;" do %>
    <%= content_tag :div, "#{scoret.me}, #{scoret.enemy}, #{scoret.point},#{scoret.SC} ", class: "score-info", style: "flex: 1;" %>
    <%= button_to "Delete", score_path(scoret), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger", style: "flex-shrink: 0; margin-left: 0px;" %>
  <% end %>
<% end %>
tempid(debug)
<%=@userdoing%>
userid(debug)
<%=@userdoingtemp%>
<%@instahero=@hero%>
優先度
<% @instahero.each do |de| %>
    <li>
      <%= de.name %>, <%= de.priority%>  
    </li>
  <% end %>
  <% @sex2.each do |de| %>
  <%de.priority=0%>
  <% end %>
  <%= link_to "完成", metanew_path, class: "btn btn-lg btn-primary" %>
  <br></br>
  データの数
  <%=Score.count%>
  <div id="scores" data-scores="<%= @score.to_json %>"></div> 
<%= javascript_include_tag 'application' %>
<%= include_gon %>



<%= label_tag 'me1', 'Me1:' %>
<%= select_tag 'me1', options_for_select(@sex2.map { |sex| [sex.name, sex.name] }), id: 'me1' %>

<%= label_tag 'me2', 'Me2:' %>
<%= select_tag 'me2', options_for_select(@sex2.map { |sex| [sex.name, sex.name] }), id: 'me2' %>

<%= label_tag 'me3', 'Me3:' %>
<%= select_tag 'me3', options_for_select(@sex2.map { |sex| [sex.name, sex.name] }), id: 'me3' %>

<%= label_tag 'me4', 'Me4:' %>
<%= select_tag 'me4', options_for_select(@sex2.map { |sex| [sex.name, sex.name] }), id: 'me4' %>
<br>
<%= label_tag 'enemy1', 'Enemy1:' %>
<%= select_tag 'enemy1', options_for_select(@sex2.map { |sex| [sex.name, sex.name] }), id: 'enemy1' %>

<%= label_tag 'enemy2', 'Enemy2:' %>
<%= select_tag 'enemy2', options_for_select(@sex2.map { |sex| [sex.name, sex.name] }), id: 'enemy2' %>

<%= label_tag 'enemy3', 'Enemy3:' %>
<%= select_tag 'enemy3', options_for_select(@sex2.map { |sex| [sex.name, sex.name] }), id: 'enemy3' %>

<%= label_tag 'enemy4', 'Enemy4:' %>
<%= select_tag 'enemy4', options_for_select(@sex2.map { |sex| [sex.name, sex.name] }), id: 'enemy4' %>

<%= label_tag 'enemy5', 'Enemy5:' %>
<%= select_tag 'enemy5', options_for_select(@sex2.map { |sex| [sex.name, sex.name] }), id: 'enemy5' %>
<br>


<button onclick="displayChampImage()">Display Image</button>

<div id="imageContainer"></div>
<div id="namesContainer"></div>
<div id="matchCountContainer"></div>
<script>
function displayChampImage() {



  var names = ['me1', 'me2', 'me3', 'me4', 'enemy1', 'enemy2', 'enemy3', 'enemy4', 'enemy5']
    .map(id => document.getElementById(id).value)
  document.getElementById('namesContainer').textContent = names;
  // @sex2のデータのnameとme1が一致する数を計算します。
 
  points=[]
  for (var i=0; i<gon.champ.length; i++) {
    points[i]=0
  }
  champs=[]
  for (var q=0; q<gon.champ.length; q++) {
    //champs[q]=String(gon.champ[q])
    champs[q]=gon.champ[q].name
  }
 //シナジーの処理
  for (var i=0; i<gon.synergy.length; i++) {
     for (var j=0; j<4; j++) {
      if (String(gon.synergy[i].me) == String(names[j])) {
      horizon=champs.indexOf(gon.synergy[i].enemy);
      points[horizon]=points[horizon]+gon.synergy[i].point
       }
       if (String(gon.synergy[i].enemy) == String(names[j])) {
      horizon=champs.indexOf(gon.synergy[i].me);
      points[horizon]=points[horizon]+gon.synergy[i].point
       }
      }
     }
  //カウンターの処理
  for (var i=0; i<gon.counter.length; i++) {
     for (var j=4; j<9; j++) {
      if (String(gon.counter[i].me) == String(names[j])) {
      horizon=champs.indexOf(gon.counter[i].enemy);
      points[horizon]=points[horizon]-gon.counter[i].point
       }
      }
     }
   for (var i=0; i<gon.counter.length; i++) {
     for (var j=4; j<9; j++) {
      if (String(gon.counter[i].enemy) == String(names[j])) {
      horizon=champs.indexOf(gon.counter[i].me);
      points[horizon]=points[horizon]+gon.counter[i].point
       }
      }
     }
     
     var pairs = champs.map(function(champ, i) {
  return { champ: champ, point: points[i] };
});

// pointsの値に基づいてソート
pairs.sort(function(a, b) {
  return b.point - a.point;
});

// ソートされたchamps配列を取得
var sortedChamps = pairs.map(function(pair) {
  return pair.champ;
});
// 以前の画像を削除します。
document.getElementById('imageContainer').innerHTML = '';

// sortedChampsの各要素に対応する画像を作成して表示します。
pairs.forEach(function(pair) {
  var img = document.createElement('img');
  img.src = '/champs/' + pair.champ + '/image';
  img.width = 140;  // 幅を100pxに設定
  img.height = 140; // 高さを100pxに設定

  // 画像の横にpointとnameを表示します。
  var text = document.createTextNode(' ' + pair.champ + ': ' + pair.point);

  var div = document.createElement('div');
  div.appendChild(img);
  div.appendChild(text);

  document.getElementById('imageContainer').appendChild(div);

  // 画像の後に改行を追加します。
  var br = document.createElement('br');
  document.getElementById('imageContainer').appendChild(br);
});
    //シチュエーションの処理  
    //matchCount = champs.indexOf(gon.synergy.enemy)
  matchCount = sortedChamps
  document.getElementById('matchCountContainer').textContent = matchCount;
}
</script>