config/routes.rb
Rails.application.routes.draw do
  get "/metanew",  to:'metamons#new'
  get "/metamonshow",  to:'metamons#show'
  get 'sessions/new'
  root "static_pages#home"
  get  "/help",    to: "static_pages#help"
  get  "/sign",  to: "scores#new"
  get  "/main",  to: "scores#main"
  get  "/daiichi",  to: "scores#daiichi"
  get  "/show",  to: "scores#show"
  get  "/tesuto",  to: "champs#new"
  get  "/hontouroku",  to: "temps#name"
  get  "/tempcon",  to: "temps#confirm"
  get  "/signup",  to: "users#new"
  get  "/usershow",  to: "users#show"
  get  "/usercon",  to: "users#confirm"
  get  "/kateindex",  to: "kategoris#index"
  get  "/useredit",  to: "users#edit"
  get    "/login",   to: "sessions#new"
  get    "/templenew",   to: "templates#new"
  get    "/templesearch",   to: "templates#search"
  get    "/tempshow",   to: "temps#show"
  get    "/scoeasy",   to: "scores#easy"
  get    "/which",   to: "metamons#which"
  
  get    "/easyscore",   to: "scores#easyscore"
  get    "/easymain",   to: "scores#easymain"
  get    "/easysituation",   to: "scores#easysituation"
  get    "/easysynergy",   to: "scores#easysynergy"
  get    "/easykihon",   to: "scores#easykihon"

  get    "/easyscoreedit",   to: "scores#easyscoreedit"
  get    "/easyedit",   to: "scores#easyedit"
  get    "/easysituationedit",   to: "scores#easysituationedit"
  get    "/easysynergyedit",   to: "scores#easysynergyedit"
  get    "/easykihonedit",   to: "scores#easykihonedit"

  get    "/tempedit",   to: "champs#edit"
  get    "/tempnameedit",   to: "temps#edit"
  get    "/catesgow",   to: "categoris#show"
  get    "/metaedit",   to: "metamons#edit"

  get "/get_position", to: "scores#get_position"
  get "/get_synergyposition", to: "scores#get_synergyposition"
  get "/get_situationposition", to: "scores#get_situationposition"
  get "/get_kihonposition", to: "scores#get_kihonposition"
  get "/get_positionedit", to: "scores#get_positionedit"
  get "/get_synergypositionedit", to: "scores#get_synergypositionedit"
  get "/get_situationpositionedit", to: "scores#get_situationpositionedit"
  get "/get_kihonpositionedit", to: "scores#get_kihonpositionedit"
  
  post '/update_or_create_data', to: 'scores#update_or_create_data'
  post '/update_or_create_synergydata', to: 'scores#update_or_create_synergydata'
  post '/update_or_create_situationdata', to: 'scores#update_or_create_situationdata'
  post '/update_or_create_dataedit', to: 'scores#update_or_create_dataedit'
  post '/update_or_create_synergydataedit', to: 'scores#update_or_create_synergydataedit'
  post '/update_or_create_situationdataedit', to: 'scores#update_or_create_situationdataedit'
  post '/update_or_create_kihondata', to: 'scores#update_or_create_kihondata'
  post '/update_or_create_kihondataedit', to: 'scores#update_or_create_kihondataedit'
  post "/login", to: "sessions#create"
  post 'reset_temp', to: 'temps#reset_temp'
  get 'edit_temp/:temp_id', to: 'champs#edit_temp', as: 'edit_temp'
  get 'edit_initiate/:truemetamonid', to: 'scores#edit_initiate', as: 'edit_initiate'
  post 'reset_score', to: 'scores#reset_score'
  post '/hontouroku', to: 'kategoris#create'
  resources :easyscores
  resources :scores
  resources :scoremaps
  resources :heros
  resources :users
  resources :champs
  resources :temps
  resources :metamons
  resources :templates
  resources :joukyous
  resources :kategoris
  resources :users do
    member do
      get :update_doing_temp
      get :update_editing_temp
    end
  end
  resources :scores do
    collection do
      post :create1
      post :create2
      post :create3
    end
  end
  get 'champs/:name/image', to: 'champs#show_image'
  resources :users do
    post 'set_tempting_false', on: :collection
  end
  resources :joukyous do
    post 'creation', on: :collection
    member do
      delete :destroy_edit_joukyou
    end
  end
  resources :champs do
    post 'set_tempting_true', on: :collection
    post 'set_editting_true', on: :collection
  
    member do
      delete :destroy_edit
    end
  end
  delete "/logout",  to: "sessions#destroy"
end

app/models/champ.rb
class Champ < ApplicationRecord
  has_one_attached :image
  belongs_to :temp, optional: true
end

app/models/checkwork.rb
class Checkwork < ApplicationRecord
end

app/models/easycounter.rb
class Easycounter < ApplicationRecord
end

app/models/easykihon.rb
class Easykihon < ApplicationRecord
end

app/models/easyscore.rb
class Easyscore < ApplicationRecord
end

app/models/easysituation.rb
class Easysituation < ApplicationRecord
end

app/models/easysynergy.rb
class Easysynergy < ApplicationRecord
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :champs, inverse_of: :group
end

app/models/hero.rb
class Hero < ApplicationRecord
end

app/models/image_word.rb
# app/models/image_word.rb
class ImageWord < ApplicationRecord
  validates :image_name, presence: true
  validates :word, presence: true
end

app/models/joukyou.rb
class Joukyou < ApplicationRecord
  has_one_attached :image
  belongs_to :temp, optional: true
end

app/models/kategori.rb
class Kategori < ApplicationRecord
  has_many :temps
  has_one_attached :image
  def self.ransackable_attributes(auth_object = nil)
    %w(name)
  end
end

app/models/metamon.rb
class Metamon < ApplicationRecord
  has_many :scores,dependent: :destroy
  has_one_attached :image
  belongs_to :user ,optional: true
  def self.ransackable_attributes(auth_object = nil)
    %w(name gamename setumei metaid)
  end
end

app/models/metum.rb
class Metum < ApplicationRecord
end

app/models/score.rb
class Score < ApplicationRecord
  belongs_to :metamon, optional: true
end

app/models/score_map.rb
class ScoreMap < ApplicationRecord
end

app/models/temp.rb
class Temp < ApplicationRecord
  belongs_to :user
  belongs_to :kategori, optional: true
  has_one_attached :image
  has_many :champs, dependent: :destroy
  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "id", "name", "temp_id", "updated_at", "user_id", "usertemp_id", "kategori_id"]
  end
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: true
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
  has_many :metamons,dependent: :destroy
  has_many :temps
  has_one_attached :image
  def self.ransackable_attributes(auth_object = nil)
    %w(created_at doingtempid doingtempuserid editingmetaid editingtempid editting email id ifnewmeta ifnewtemp metating name tempting updated_at)
  end
end

app/controllers/temps_controller.rb
class TempsController < ApplicationController
  def index
    @q = Temp.ransack(params[:q])
    @tempall = @q.result(distinct: true)
  end
  def confirm
    @q = Temp.ransack(params[:q])
    @tempall = @q.result(distinct: true)
  end
  def name
    @newtemp=Temp.new
  end
  def edit
    @temp = Temp.where(user_id: current_user.id, temp_id: current_user.editingtempid).first
  end
  def show
    @thetemp = Champ.where(user_id: params[:user_id], temp_id: params[:id])
    @thejoukyou = Joukyou.where(user_id: params[:user_id], temp_id: params[:id])
  end
  def reset_temp
    Champ.where(user_id: current_user.id, temp_id: current_user.ifnewtemp).destroy_all
    Joukyou.where(user_id: current_user.id, temp_id: current_user.ifnewtemp).destroy_all
    current_user.update_columns(tempting: false)
    redirect_to root_path, notice: 'Temp has been reset.'
  end
  def create
    @newtemp=Temp.new(temp_params)
    @newtemp.user_id = current_user.id
    @newtemp.temp_id = current_user.ifnewtemp
    
    if @newtemp.save
      current_user.increment!(:ifnewtemp)
    else
      render 'name'
    end
  end
  def update
    Rails.logger.info "Update action started"
    @temp = Temp.where(user_id: current_user.id, temp_id: current_user.editingtempid).first
  
    if @temp.update(temp_params)
      Rails.logger.info "Update successful, redirecting to usershow_path"
      redirect_to usershow_path(id:current_user.id), notice: 'Temp was successfully updated.'
    else
      Rails.logger.info "Update failed, redirecting to usershow_path"
      redirect_to usershow_path(id:current_user.id)
    end
    Rails.logger.info "Update action ended"
  end
  def destroy
    # Your code here
  end
  
  private

    def temp_params
      params.require(:temp).permit(:name, :image, :kategori_id)
    end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/new_helper.rb
module NewHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/temps/confirm.html.erb
<style>

  .link-box {
    display: flex; /* 追加: 子要素を行方向に配置します */
    align-items: center; /* 追加: 子要素を垂直方向に中央揃えにします */
    margin-bottom: 20px;
  }
  .link-box img{
    border-radius: 10px; /* 追加: 背景の角をなくします */
    width: 100px; /* 画像の幅を指定します */
    height: 100px; /* 画像の高さを指定します */
    background-color: white; /* 背景色を白にします */
    border: 1px solid #ddd; /* 枠線を灰色にします */
    display: flex; /* 子要素を行方向に配置します */
    align-items: center; /* 子要素を垂直方向に中央揃えにします */
    justify-content: center; /* 子要素を水平方向に中央揃えにします */
  }
  .default-image {
    border-radius: 10px; /* 追加: 背景の角をなくします */
    width: 100px; /* 画像の幅を指定します */
    height: 100px; /* 画像の高さを指定します */
    background-color: white; /* 背景色を白にします */
    border: 1px solid #ddd; /* 枠線を灰色にします */
    display: flex; /* 子要素を行方向に配置します */
    align-items: center; /* 子要素を垂直方向に中央揃えにします */
    justify-content: center; /* 子要素を水平方向に中央揃えにします */
  }
  .default-image img {
    object-fit: contain; /* 追加: 画像が枠内に収まるように調整します */
    width: 100%; /* 追加: 画像の幅を100%に設定します */
    height: 100%; /* 追加: 画像の高さを100%に設定します */
  }
  .search-form {
    background-color: #666; /* グレー色をもう少し濃くします */
    border-radius: 25px; /* 角をなくして丸みを帯びた形にします */
    padding: 10px; /* 内側の余白を追加します */
    display: flex; /* ラベルと入力エリアを一行に並べます */
    align-items: center; /* ラベルと入力エリアを中央揃えにします */
  margin-bottom: 20px; /* 追加: 要素間に空白を追加します */
  }
  .search-form label {
    margin-right: 10px; /* ラベルと入力エリアの間に余白を追加します */
  }
  .search-form input[type="text"] {
    border: none; /* テキストボックスの枠線を消します */
    background-color: transparent; /* テキストボックスの背景色を透明にします */
    flex-grow: 1; /* 入力エリアを可能な限り広げます */
    border-radius: 15px; /* 入力エリアの角を丸くします */
  }
  li {
    list-style-type: none;
  }
</style>

<li>
<%= search_form_for @q, html: { class: 'search-form' } do |f| %>
  <%= f.search_field :name_cont %>
  <%= f.submit "テンプレートを検索" %>
<% end %>

<div class="link-container">
  <% @tempall.each do |temall| %>
    <div class="link-box">
      <% if temall.image.attached? %>
        <%= image_tag(url_for(temall.image), class: "icon") %>
      <% else %>
      <div class="default-image">
        <%= image_tag("登山のアイコン4.png", class: "icon") %>
      </div>
      <% end %>
      <%= link_to temall.name, {controller: "temps", action: "show", user_id: temall.user_id, id: temall.temp_id} %>    
    </div>
    <hr>
  <% end %>
</div>

app/views/temps/edit.html.erb
<%= form_for @temp, url: temp_path(@temp), method: :patch do |f| %>
  <% if @temp.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@temp.errors.count, "error") %> prohibited this temp from being saved:</h2>

      <ul>
      <% @temp.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/temps/index.html.erb
<style>

  .link-box {
    display: flex; /* 追加: 子要素を行方向に配置します */
    align-items: center; /* 追加: 子要素を垂直方向に中央揃えにします */
    margin-bottom: 20px;
  }
  .link-box img{
    border-radius: 10px; /* 追加: 背景の角をなくします */
    width: 100px; /* 画像の幅を指定します */
    height: 100px; /* 画像の高さを指定します */
    background-color: white; /* 背景色を白にします */
    border: 1px solid #ddd; /* 枠線を灰色にします */
    display: flex; /* 子要素を行方向に配置します */
    align-items: center; /* 子要素を垂直方向に中央揃えにします */
    justify-content: center; /* 子要素を水平方向に中央揃えにします */
  }
  .default-image {
    border-radius: 10px; /* 追加: 背景の角をなくします */
    width: 100px; /* 画像の幅を指定します */
    height: 100px; /* 画像の高さを指定します */
    background-color: white; /* 背景色を白にします */
    border: 1px solid #ddd; /* 枠線を灰色にします */
    display: flex; /* 子要素を行方向に配置します */
    align-items: center; /* 子要素を垂直方向に中央揃えにします */
    justify-content: center; /* 子要素を水平方向に中央揃えにします */
  }
  .default-image img {
    object-fit: contain; /* 追加: 画像が枠内に収まるように調整します */
    width: 100%; /* 追加: 画像の幅を100%に設定します */
    height: 100%; /* 追加: 画像の高さを100%に設定します */
  }
  .search-form {
    background-color: #666; /* グレー色をもう少し濃くします */
    border-radius: 25px; /* 角をなくして丸みを帯びた形にします */
    padding: 10px; /* 内側の余白を追加します */
    display: flex; /* ラベルと入力エリアを一行に並べます */
    align-items: center; /* ラベルと入力エリアを中央揃えにします */
  margin-bottom: 20px; /* 追加: 要素間に空白を追加します */
  }
  .search-form label {
    margin-right: 10px; /* ラベルと入力エリアの間に余白を追加します */
  }
  .search-form input[type="text"] {
    border: none; /* テキストボックスの枠線を消します */
    background-color: transparent; /* テキストボックスの背景色を透明にします */
    flex-grow: 1; /* 入力エリアを可能な限り広げます */
    border-radius: 15px; /* 入力エリアの角を丸くします */
  }
  li {
    list-style-type: none;
  }
</style>

<li>
<%= search_form_for @q, html: { class: 'search-form' } do |f| %>
  <%= f.search_field :name_cont %>
  <%= f.submit "テンプレートを検索" %>
<% end %>

<div class="link-container">
  <% @tempall.each do |temall| %>
    <div class="link-box">
      <% if temall.image.attached? %>
        <%= image_tag(url_for(temall.image), class: "icon") %>
      <% else %>
      <div class="default-image">
        <%= image_tag("登山のアイコン4.png", class: "icon") %>
      </div>
      <% end %>
      <%= link_to temall.name, {controller: "temps", action: "show", user_id: temall.user_id, id: temall.temp_id} %>    
    </div>
    <hr>
  <% end %>
</div>

app/views/temps/name.html.erb
<h1>テンプレートを登録</h1>
ヒーローとシチュエーションを合わせてテンプレートとして登録します。
<br>テンプレート集の名前と画像を決めてください。
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with(model: @newtemp, url: set_tempting_false_users_path, method: :post) do |f| %>
      <%= f.label :名前 %>
      <%= f.text_field :name %>

      <%= f.label :画像 %>
      <%= f.file_field :image %>

      <%= f.label :ゲームカテゴリー %>
      <%= f.collection_select :kategori_id, Kategori.all, :id, :name, prompt: "Select a Kategori" %>

      

      <%= f.submit "登録", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>
ゲームがありませんか？
カテゴリーを追加
<%= form_with(model: @kategori, url: hontouroku_path, local: true) do |f| %>
  <%= f.label :名前 %>
  <%= f.text_field :name, name: 'kategori[name]' %>

  <%= f.label :画像 %>
  <%= f.file_field :image, name: 'kategori[image]' %>

  <%= f.submit "カテゴリーを追加", class: "btn btn-primary" %>
<% end %>

app/views/temps/show.html.erb
<%if current_user.metating%>
<h1>現在作成中のMetaがあります</h1>
作成中のMetaを削除するか、編集を完了してください<br>
<%= link_to '作成中のMetaを編集する', scoeasy_path%>
<%= link_to '作成中のMetaを完全に削除する', '#'%>
<%else%>
<h1>Hero</h1>
<% @thetemp.each do |sap| %>
<%=sap.name%>
<% if sap.image.attached? %>
    <%= image_tag sap.image.variant(resize_to_fill: [100, 100]).processed, class: "mr-3" %>
<% end %>
<%end%>
<h1>Situation</h1>
<% @thejoukyou.each do |sa| %>
<%=sa.name%>
<% if sa.image.attached? %>
    <%= image_tag sa.image.variant(resize_to_fill: [100, 100]).processed, class: "mr-3" %>
<% end %>
<%end%>
<%= link_to 'これを使ってメタを作る', update_doing_temp_user_path(current_user, user_id: params[:user_id], temp_id: params[:id]) %>
<% if current_user.id == params[:user_id].to_i %>
  <br><%= link_to 'テンプレートを編集する', update_editing_temp_user_path(current_user, user_id: params[:user_id], temp_id: params[:id]) %>
<% end %>
<% end %>